# Generated by Django 4.2.16 on 2024-09-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default='Anonymous', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endereco',
            name='cep',
            field=models.CharField(default='00000000', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endereco',
            name='uf',
            field=models.CharField(default='SP', max_length=2),
            preserve_default=False,
        ),
    ]
