# Generated by Django 4.2.16 on 2024-10-12 13:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0005_alter_endereco_bairro_alter_endereco_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='data_inscricao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='professor',
            name='disciplina',
            field=models.CharField(choices=[('MT', 'Matemática'), ('PT', 'Português'), ('HI', 'História'), ('GE', 'Geografia'), ('FI', 'Física'), ('QU', 'Química'), ('BI', 'Biologia')], max_length=2),
        ),
    ]
