# Generated by Django 4.2.16 on 2024-10-13 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0008_alter_historico_nota1_alter_historico_nota2_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='historico',
            unique_together={('aluno', 'disciplina', 'periodo')},
        ),
    ]
